#!/usr/bin/env bash
#
# apply-stub.sh — put the jharness invariant block into a project's AGENTS.md
# and CLAUDE.md without clobbering anything the project wrote itself.
#
# The block is the harness-invariant part of the context tree: the pointer to
# docs/agents/coding_guidelines.md, the "Never in this repository" rules, and the
# docs/agents index. It is delimited by a marker pair and owns only what is
# between the markers:
#
#   <!-- jharness:start -->
#   ...
#   <!-- jharness:end -->
#
# Three on-disk cases, one outcome each:
#
#   file absent        seed  — write "# AGENTS.md" + the block
#   block present      sync  — replace the block in place, leave the rest alone
#   block absent       graft — append the block after the project's own content
#
# A file carrying the /ai-context ownership banner is left alone: that pipeline
# generates the whole file, block included, and the two must not fight.
#
# Usage:
#   scripts/apply-stub.sh --source <harness-dir> [--check] [target]
#
# Output, one record per artifact:
#   STUB <AGENTS|CLAUDE> <status> <path>
#
# Status, apply mode: seeded | grafted | synced | current | generated
# Status, --check:    absent | no-block | outdated | current | generated
#
# Exit: 0 = ran; 2 = usage/precondition.

set -uo pipefail

START='<!-- jharness:start -->'
END='<!-- jharness:end -->'

SRC=""
CHECK=0
TARGET=""

die() { echo "apply-stub: $1" >&2; exit 2; }

while [ $# -gt 0 ]; do
  case "$1" in
    --source) [ $# -ge 2 ] || die "--source needs a path"; SRC="$2"; shift 2 ;;
    --check) CHECK=1; shift ;;
    -h|--help) sed -n '2,33p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*) die "unknown option $1" ;;
    *) [ -z "$TARGET" ] || die "only one target allowed"; TARGET="$1"; shift ;;
  esac
done

[ -n "$SRC" ] || die "--source <harness-dir> is required"
[ -d "$SRC/stubs" ] || die "$SRC has no stubs/ directory — not a jharness tree"
TARGET="${TARGET:-$PWD}"
[ -d "$TARGET" ] || die "target $TARGET is not a directory"

# block_of <file> — the marked block as it stands in that file, markers included
block_of() {
  awk -v s="$START" -v e="$END" '$0==s{f=1} f{print} $0==e{f=0}' "$1"
}

# swap_block <file> <stub> — the file with its block replaced by the stub's
swap_block() {
  awk -v stub="$2" -v s="$START" -v e="$END" '
    $0 == s { inblock=1; while ((getline l < stub) > 0) print l; close(stub); next }
    $0 == e { inblock=0; next }
    !inblock { print }
  ' "$1"
}

apply_one() {
  local name="$1"
  local stub="$SRC/stubs/$name.stub"
  local local_file="$TARGET/$name.md"
  local rel="$name.md"

  [ -f "$stub" ] || die "source is missing stubs/$name.stub"

  if [ ! -f "$local_file" ]; then
    if [ "$CHECK" -eq 1 ]; then echo "STUB $name absent $rel"; return; fi
    { printf '# %s\n\n' "$rel"; cat "$stub"; } > "$local_file.tmp.$$" \
      && mv "$local_file.tmp.$$" "$local_file"
    echo "STUB $name seeded $rel"
    return
  fi

  if grep -Fq '<!-- Generated by /ai-context.' "$local_file"; then
    echo "STUB $name generated $rel"
    return
  fi

  if ! grep -Fxq "$START" "$local_file"; then
    if [ "$CHECK" -eq 1 ]; then echo "STUB $name no-block $rel"; return; fi
    { cat "$local_file"; printf '\n'; cat "$stub"; } > "$local_file.tmp.$$" \
      && mv "$local_file.tmp.$$" "$local_file"
    echo "STUB $name grafted $rel"
    return
  fi

  if block_of "$local_file" | cmp -s - "$stub"; then
    echo "STUB $name current $rel"
    return
  fi

  if [ "$CHECK" -eq 1 ]; then echo "STUB $name outdated $rel"; return; fi
  swap_block "$local_file" "$stub" > "$local_file.tmp.$$" \
    && mv "$local_file.tmp.$$" "$local_file"
  echo "STUB $name synced $rel"
}

apply_one AGENTS
apply_one CLAUDE
exit 0
